[package]
name = "jgze"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive"] }
flate2 = "1.0"
serde_json = "1.0"
tempfile = "3.10"
anyhow = "1.0"
