name: Release

on:
  push:
    tags:
      - 'v[0-9]+.*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          # Linux (x86_64)
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest

          # macOS (Intel)
          - target: x86_64-apple-darwin
            os: macos-latest

          # macOS (Apple Silicon)
          - target: aarch64-apple-darwin
            os: macos-latest

          # Windows (x86_64)
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build and upload binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: jgze # same as package name on Cargo.toml
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
